### PR TITLE
Add a Makefile to prepare the repo before starting to contribute

### PR DESCRIPTION
**Pull request by aurelien-reeves**
To run the tests for the Ruby or Java packages, we need to first build the Javascript package and then copy the assets from it.

When we want to do this from a release GitHub workflow, we are stuck because GitHub won't let us nest the workflows, so if `test-java`, say, already depends on `build-javascript` then `release-java` can't call `test-java`.

In any case, this dependency is probably useful to express outside of GitHub's CI, so that developers can also copy these files around if they need to work on the Ruby or Java packages on their local environment.

So we're going to move this step of the build into a `Makefile`.

Fixes: #3

### CODE REVIEW

**Comment by mattwynne** [comment]
I'm interested in whether we can simplify the `Makefile` some more. It seems like the change in asset filename (e.g. from `main.js` to `cucumber-html.js`) is unfortunate as it makes it harder to generate these lists of files, so they're currently listed out one at a time. I wonder how necessary those renames are?

**Comment by aurelien-reeves** [comment]
@mattwynne any objection with my addition?
I've added some auto-documentation to the makefile. What do you think of it? Would you prefer I revert it?

**Comment by mattwynne** [comment]
> @mattwynne any objection with my addition? I've added some auto-documentation to the makefile. What do you think of it? Would you prefer I revert it?

I like it!

I think we may have different behaviour on the OSX `seb` and the linux one. This is what I see:

```
Please use 'make <target>' where <target> is one of:

help: ## Show this help
prepare: $(ruby_assets) $(java_assets) ## Build javascript module and copy required artifacts to java and ruby projects
clean: ## Remove javascript built module and related artifacts from java and ruby projects
```

Is the `$(ruby_assets) $(java_assets)` bit meant to be shown? I can't quite understand the `sed` command but I see the capture groups and the `\1` and `\3` suggesting it's supposed to only show the target name and description, not the dependencies. Maybe we could try another option from https://gist.github.com/prwhite/8168133?

**Comment by mattwynne** [comment]
I tried a different one, looks nice on my Mac:

Screenshot 2022-02-08 at 11 27 19 AM

Does it work for you?

**Comment by aurelien-reeves** [comment]
Great!

**Pull request merged**
